@HotelListing.Api_HostAddress = http://localhost:5106/
@id=1

GET {{HotelListing.Api_HostAddress}}api/hotels
Accept: application/json

###

POST {{HotelListing.Api_HostAddress}}api/hotels
Accept: application/json
Content-Type: application/json

{
    "id": 3,
    "name": "New Grand Plaza",
    "address": "123 Main St",
    "rating": 4.7
}

###

GET {{HotelListing.Api_HostAddress}}api/hotels/{{id}}
Accept: application/json

###

PUT {{HotelListing.Api_HostAddress}}api/hotels/{{id}}
Content-Type: application/json

{
    "name": "Grand Plaza",
    "address": "123 Main St",
    "rating": 4.5
}
###

DELETE {{HotelListing.Api_HostAddress}}api/hotels/{{id}}

###
